version: '3.9'
name: fast-api-dev

services:

  dev-db:
    image: postgres:alpine3.19
    restart: always
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

